### ISSUE TITLE
[Step_f2]Crash reason: Assertion 'AddTo.size() != NumAdd' failed

### ISSUE THREAD

**Issue by Breeder2** [stepmania/stepmania#1439] opened 2017-05-06 08:10 UTC
Dear sirs,

I need help because below error message occur when i tried to start game.
In addition, i followed all instructions in below web site and reinstalled game files.
http://stepf2.blogspot.kr/p/screenshots-previews.html

However, same problem still occured.
Please help me ASAP.

P.S.
I'm windows 8.1K user.
Directx version is 11.

StepMania v5.0 beta 3 crash report (build 7, 20170407 @ 23:43:04 Hora est?dar de Argentina)
--------------------------------------

Crash reason: Assertion 'AddTo.size() != NumAdd' failed

Thread: Main thread
        RageTextureManager.cpp:123 RageTextureManager::LoadTexture(/Themes/_fallback/Fonts/Common default 2x1.png).
        RageTextureManager.cpp:123 RageTextureManager::LoadTexture(/Themes/Fiesta 2/Fonts/MenuTimer numbers 4x3.png).
        BitmapText.cpp:166 BitmapText::LoadFromFont(/Themes/Fiesta 2/Fonts/MenuTimer numbers.ini)
        FontManager.cpp:40 FontManager::LoadFont(/Themes/Fiesta 2/Fonts/MenuTimer numbers.ini).
        SongManager.cpp:2274 Assertion 'AddTo.size() != NumAdd' failed
Thread: Decode thread
        RageSoundDriver_Generic_Software.cpp:204 
        RageSoundDriver_Generic_Software.cpp:204 
        RageSoundDriver_Generic_Software.cpp:204 
        RageSoundDriver_Generic_Software.cpp:204 
        RageSoundDriver_Generic_Software.cpp:204 
Thread: Mixer thread
Thread: Music thread
Thread: Worker thread (MemoryCardWorker)
Thread: Worker thread (/@mc1int/)
Thread: Worker thread (/@mc2int/)
Thread: DirectInput thread
        InputHandler_DirectInput.cpp:755 
        InputHandler_DirectInput.cpp:731 
        InputHandler_DirectInput.cpp:750 
        InputHandler_DirectInput.cpp:755 
        InputHandler_DirectInput.cpp:731 
Thread: Streaming sound buffering

debug resource file 'C:\Users\lee\Downloads\STEP_F2_V1_14 (Steppack 2.14)\STEP_F2.vdi': CreateFile failed (지정된 파일을 찾을 수 없습니다.).

Static log:
StepMania v5.0 beta 3
Compiled 20170407 @ 23:43:04 Hora est?dar de Argentina (build 7)
Log starting 2017-05-06 17:00:18
Loading window: win32
Windows 6.2 (Win8) build 9200 []
Memory: 4095mb total, 4095mb swap (4095mb swap avail)
Video driver: Intel(R) HD Graphics 4600 [Intel Corporation]
              10.18.10.3540, 3-30-2014 [pci\ven_8086&dev_0416&subsys_397817aa]
Drive: "WDC     WD10SPCX-24HWST102.0" Driver: iaStorA DMA: N/A
Sound device 0: Speakers(Realtek High Definitio, 6.3, MID 1, PID 100 
Sound device 1: Realtek Digital Output(Realtek , 6.3, MID 1, PID 100 
WaveOut software mixing at 44100 hz
Sound driver: WaveOut
Lights driver: SystemMessage
Lights driver: Export
Video renderers: 'd3d,opengl'
WARNING: RageDisplay_D3D::TryVideoMode( 0, 1920, 1080, 32, 0, 1 )
D3D Fullscreen 1920x1080 32 color 16 texture 60Hz Vsync NoSmoothLines
DInput: Enumerating device - Type: 0x00000A13 Instance Name: "키보드" Product Name: "키보드"
DInput: Enumerating device - Type: 0x00000112 Instance Name: "마우스" Product Name: "마우스"
Found 2 DirectInput devices:
   0: '?ㅻ낫?? axes: 0, hats: 0, buttons: 256 (buffered)
   1: '留덉슦?? axes: 3, hats: 0, buttons: 5 (buffered)
Mixing underruns: 1
Players joined: P1
Language: en
Current renderer: Direct3D
Theme: Fiesta 2

Partial log:
01:36.864: RageSound: Load "/Themes/Fiesta 2/Sounds/Sounds/SELECT.mp3" (precache: 1)
01:36.874: RageSound: Load "/Themes/Fiesta 2/Sounds/Sounds/D_MOVE.wav" (precache: 0)
01:36.875: Starting thread: Streaming sound buffering
01:36.875: RageSound: Load "/Themes/Fiesta 2/Sounds/Sounds/BAD.wav" (precache: 1)
01:36.875: RageSound: Load "/Themes/Fiesta 2/Sounds/Categories/NEW TUNES.mp3" (precache: 1)
01:36.884: RageSound: Load "/Themes/Fiesta 2/Sounds/Categories/ORIGINAL.mp3" (precache: 1)
01:36.897: RageSound: Load "/Themes/Fiesta 2/Sounds/Categories/K-POP.wav" (precache: 1)
01:36.902: RageSound: Load "/Themes/Fiesta 2/Sounds/Categories/WORLD MUSIC.mp3" (precache: 1)
01:36.912: RageSound: Load "/Themes/Fiesta 2/Sounds/Categories/J-MUSIC.ogg" (precache: 1)
01:36.926: RageSound: Load "/Themes/Fiesta 2/Sounds/Sounds/TIMER_TICK.mp3" (precache: 0)

-- End of report

**Comment by dguzek** [comment] 2017-05-06 08:12
Duplicate of #1438.

We cannot investigate or fix bugs in StepF2. You can contact them via their Facebook page [here](https://www.facebook.com/StepF2-478582152222113).

**Closed by dguzek** 2017-05-06 08:12 UTC

**Comment by Breeder2** [comment] 2017-05-06 08:35
Sorry, i alreay tried to contact in charge of person by facebook.
But i can't.
So,please let me know contact point for  key person who can solve this problem.
Best regards.


네이버 메일 앱에서 보냈습니다.

-----Original Message-----
보낸사람: "Dan Guzek" &lt;notifications@github.com&gt;
받는사람: "stepmania/stepmania" &lt;stepmania@noreply.github.com&gt;
참조: "Breeder2" &lt;cheolbong85@naver.com&gt;,"Author" &lt;author@noreply.github.com&gt;
날짜: 2017.05.06 오후 05:12:11
제목: Re: [stepmania/stepmania] [Step_f2]Crash reason: Assertion 'AddTo.size() != NumAdd' failed (#1439)



Closed #1439.

**Comment by Flameshadowxeroshin** [comment] 2017-05-06 23:20
I don't even know exactly who the StepF2 developers are, sorry. The only channels we have are the same ones you have.
