### ISSUE TITLE
Editor Audio Preview is Out of Sync

### ISSUE THREAD

**Issue by cptnoblivious** [stepmania/stepmania#956] opened 2015-12-09 17:04 UTC
Specifically, previewing your work in the editor starting from any arbitrary beat (Shift+P) does not start the music at the correct time.  This issue is not apparent when previewing from the first beat of a song.

**Comment by kyzentun** [comment] 2015-12-09 17:06
Don't use a variable bit rate MP3.  This is a duplicate of #369.

**Closed by kyzentun** 2015-12-09 17:06 UTC
Labels: duplicate
