### ISSUE TITLE
GtkModules dependencies are missing harfbuzz include path

### ISSUE THREAD

**Issue by mwkroening** [stepmania/stepmania#1850] opened 2019-08-07 21:24 UTC
Building on Arch Linux with `WITH_GTK2=1` results in:
```bash
# [...]
Scanning dependencies of target GtkModule
[ 47%] Building CXX object src/CMakeFiles/GtkModule.dir/arch/LoadingWindow/LoadingWindow_GtkModule.cpp.o
In file included from /usr/include/pango-1.0/pango/pango-font.h:25,
                 from /usr/include/pango-1.0/pango/pango-attributes.h:25,
                 from /usr/include/pango-1.0/pango/pango.h:25,
                 from /usr/include/gtk-2.0/gdk/gdktypes.h:37,
                 from /usr/include/gtk-2.0/gdk/gdkscreen.h:32,
                 from /usr/include/gtk-2.0/gdk/gdkapplaunchcontext.h:31,
                 from /usr/include/gtk-2.0/gdk/gdk.h:32,
                 from /usr/include/gtk-2.0/gtk/gtk.h:32,
                 from /home/mkroening/.cache/yay/stepmania-git/src/stepmania/src/arch/LoadingWindow/LoadingWindow_GtkModule.cpp:8:
/usr/include/pango-1.0/pango/pango-coverage.h:28:10: fatal error: hb.h: No such file or directory
   28 | #include <hb.h>
      |          ^~~~~~
compilation terminated.
make[2]: *** [src/CMakeFiles/GtkModule.dir/build.make:63: src/CMakeFiles/GtkModule.dir/arch/LoadingWindow/LoadingWindow_GtkModule.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:350: src/CMakeFiles/GtkModule.dir/all] Error 2
make: *** [Makefile:152: all] Error 2
```

This is because harfbuzz' include path is `/usr/include/harfbuzz/` on my system.

**Comment by mkroening** [comment] 2019-08-10 17:22
I agree to @shakesoda, that such a workaround is strange.

As it turns out on Ubuntu harfbuzz does have the same include path. See: https://packages.ubuntu.com/xenial/amd64/libharfbuzz-dev/filelist

I am not sure why this workaround is needed on my system. There might be an issue with gtk packaging on Arch Linux after all.

**Comment by mkroening** [comment] 2019-08-10 21:21
Indeed this is not required when using gtk3 (see #1855). So I now have kind of a circular dependency. :smile:

So I'll drop #1852 from the other PRs and close this once we use gtk3.

**Comment by mkroening** [comment] 2020-06-21 21:49
This probably was an issue with Arch packages. I can't reproduce it anymore.

**Closed by mkroening** 2020-06-21 21:49 UTC
