### ISSUE TITLE
Stepmania compliation errors on Japanese locale

### ISSUE THREAD

**Issue by PortalLife** [stepmania/stepmania#680] opened 2015-06-10 22:13 UTC
http://portal-life.s-ul.eu/usmBsImR

I was met with these errors when trying to compile on Japanese locale - i had to switch my system to US locale in order to fix the problem.

Was using VS2013.

**Comment by wolfman2000** [comment] 2015-06-10 22:14
Duplicate of #76. My bad for not catching that earlier.

**Closed by wolfman2000** 2015-06-10 22:14 UTC
Labels: duplicate
