### ISSUE TITLE
Change Notes' DrawOrder from furthest to closest during gameplay

### ISSUE THREAD

**Issue by sillybear** [stepmania/stepmania#167] opened 2014-05-15 14:01 UTC
The current build states that arrows closer to stepzone are placed to the bottom layer so playing very small speed mod like x0.25 (or even x1 full of 16th streams) is more confusing. I suggest to make the notes closer to stepzone be on top layer.

**Comment by Kaiveran** [comment] 2016-05-29 22:50
Split in image is just for aesthetic purposes it seems, not to indicate reverse.

+1 for making this a noteskin setting per-column

I tried messing with the noteskin metric myself, to no avail. @hanubeki somehow got it working in 5.0,  don't know how though. He didn't respond to my comment and has since deleted the video he demonstrated it in.

While we're on the subject, @kyzentun, is there anything in the NewSkin/NewField system that might accomodate this?

**Comment by kyzentun** [comment] 2016-05-29 23:18
I haven't bothered to implement it largely because I don't see the point.  If the notes are overlapping, the speed mod is too low anyway.

**Comment by sillybear** [comment] 2016-06-04 23:55
@kyzentun Try to look at simfiles like MAX.(period), Over The "Period", Pluto Relinquish and many more that have minimum bpm changes below 100 and maximum bpm at least thrice their multiples. It would be nice to have a draw order user preference for it. I'm sure majority prefer the old SM3.9 style for the simfiles like these.

**Comment by Kaiveran** [comment] 2016-06-06 07:54
Yeah, basically what sillybear said. BPM change and Stop gimmicks are still alive, and even though they are almost totally replaceable by the new Scroll Rate/Speed timing segments (perhaps completely replaceable actually, now that the NewField can manipulate quants), the visual results are similar and their effects can extend to CMod play as well, thus the importance of this issue. This is especially of interest to pad players, or at least pad players who aren't in the ballpark of iamchris4life, Happy Feet, etc. who almost universally use lower speedmods than keyboard players, thus having notes overlap more.

However, I've changed my mind. **I think a DrawOrder preference would belong to the realm of _modifiers_ and not noteskins**, since it really doesn't have anything to do with how the noteskin itself is built; it just changes how it's displayed. Everything else from the former metrics.ini seemed to be getting copied to the noteskin Lua, so naturally I thought that DrawOrder should've been included in it as a per-column setting to bring it up to date, but that on its face means that Draw Order will be only modifiable by going into the noteskin files and messing with them. If it's able to be controlled by skin_parameters, and thus be customizable, you inevitably have the problem where some noteskin authors can't or won't include it and people will have to dig through the files to change it anyway. So maybe a per-column "Draw Priority" modifier is the most viable option.

If I may address you personally, @kyzentun, I have been lurking around certain forums and have witnessed firsthand the thanklessness of your work and how toxic some communities can be. I appreciate the huge amount of work you've been doing for SM recently, and I wish I wasn't just another fucklord who keeps demanding things of you, even if I am respectful and have decent enough ideas. I hope to someday learn enough coding myself to ease your pain, because I want to see SM succeed and be the best it can be. My deepest sympathies.

**Comment by kyzentun** [comment] 2016-06-06 17:25
Does it really need to be a modifier?  Does it really need to be settable at all?  If the closer notes should be on top, I can just change push_back to push_front and have it hardcoded that way.

There are actually several lua settable bools in the NewField that aren't modifiers because I haven't figured out an optimized way of making them settable by time or wave function the way the other modifiers are.  (add_y_offset_to_position, holds_skewed_by_mods, twirl_holds, use_moddable_hold_normal should all be settable by the timed mod system, for example.)

@Kaiveran That stuff doesn't belong in issue reports.  You can use IRC or email to talk about stuff that isn't directly about bugs and features.  People asking for features doesn't bother me.  What irritates me is when people deny the existence of what I've already done or blame me for problems caused by someone else.

**Comment by kyzentun** [comment] 2016-06-10 20:48
I've hardcoded it the other way around for now.
https://github.com/stepmania/stepmania/commit/e4969053f21ef53163a4e6a66fe909cc2eb90c56

**Comment by shakesoda** [comment] 2019-03-16 00:18
closing, as this is fixed in both 5.1 and 5.2

**Closed by shakesoda** 2019-03-16 00:18 UTC
