### ISSUE TITLE
Step zone not flashing 

### ISSUE THREAD

**Issue by tcorrie** [stepmania/stepmania#632] opened 2015-05-19 04:38 UTC
On 5.0.8, whenever I play a song, the step zone doesn't flash and the arrows segments don't change

**Comment by kyzentun** [comment] 2015-05-19 04:40
This is probably a duplicate of #601 and probably fixed by https://github.com/stepmania/stepmania/commit/f5aec7ed4b282ba1a95c0cbc2975612c834322aa
Just to be sure, tell us what noteskin you're using and someone can test it.

**Comment by tcorrie** [comment] 2015-05-19 04:42
oldnote is the name of the skin

**Comment by kyzentun** [comment] 2015-05-19 04:44
I need a link if you have one, just to be absolutely sure it's tested with the same noteskin.

**Comment by tcorrie** [comment] 2015-05-19 04:49
https://www.dropbox.com/sh/7vzaolih7ltfb0r/AABAHhTG6SBgGljGBqIWJ2mGa?dl=0

**Comment by kyzentun** [comment] 2015-05-19 06:49
Testing confirmed that this is a duplicate and has been fixed in the code, so I'm closing this issue.
Not sure when 5.0.9 will be released, we haven't decided on a release date yet.

**Closed by kyzentun** 2015-05-19 06:49 UTC

**Comment by tcorrie** [comment] 2015-05-19 07:00
Thanks!
