### ISSUE TITLE
Error when linking: relocation can not be used when making a shared object; recompile with -fPIC

### ISSUE THREAD

**Issue by lukeoftheaura** [stepmania/stepmania#1605] opened 2017-12-10 17:12 UTC
When I try and compile stepmania (both from master and from 5.0.12) I get this error when linking:

```
[100%] Linking CXX executable ../../stepmania
/usr/bin/ld: ../../extern/libmmmagic/linux-64bit/libmmmagic.a(mmmagic.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: ../../extern/libmmmagic/linux-64bit/libmmmagic.a(minimaidhid.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: ../../extern/libmmmagic/linux-64bit/libmmmagic.a(update.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
make[2]: *** [src/CMakeFiles/StepMania.dir/build.make:10906: ../stepmania] Error 1
make[1]: *** [CMakeFiles/Makefile2:499: src/CMakeFiles/StepMania.dir/all] Error 2
make: *** [Makefile:152: all] Error 2

```

OS: Antergos Linux 64-bit

**Comment by concubidated** [comment] 2017-12-10 18:09
cmake .. -DWITH_MINIMAID=OFF

This is a duplicate of #1352

**Closed by concubidated** 2017-12-10 18:09 UTC
Labels: duplicate

**Comment by latot** [comment] 2018-03-31 21:28
Hi, now there is a version with fPIC enabled of mmmagick, i test it and works, maybe use it when fpic is enabled?
