### ISSUE TITLE
Found a fix for the broken Pump TickHolds

### ISSUE THREAD

**Issue by D-to-the-K** [stepmania/stepmania#729] opened 2015-07-19 12:21 UTC
When playing Pump, you'd usually have a very large time window to let go of a hold note and regrab it without missing any checkpoints. Currently you miss a lot very fast. Some friends and I managed to track down the problem:
https://github.com/stepmania/stepmania/commit/b61e8783b56107d438f67f7f3b9ea5560367c9da

As I'm unfamiliarized with Git, I just left a comment there and reported the issue here. Thanks for understanding and keep up the good work :)

**Comment by wolfman2000** [comment] 2015-07-19 12:23
I don't ever recall Pump being generous on missing ticks. Then again, I am due to play again, so I guess I can confirm.

What version of Pump are you specifically referring to at the start?

**Comment by D-to-the-K** [comment] 2015-07-19 12:26
Basically every version since NX2. We're working on a fork that uses timing windows very close to the arcade game, and we noticed that the long notes behaved much better before beta 3. As it turns out, this is why.

**Comment by wolfman2000** [comment] 2015-07-19 22:42
@D-to-the-K First version of an attempted fix is made in #730. Are you or your companions able to confirm if this is valid?

**Comment by wolfman2000** [comment] 2015-07-20 02:12
Resolved via 76d07bc.

**Closed by wolfman2000** 2015-07-20 02:12 UTC

**Comment by D-to-the-K** [comment] 2015-07-20 03:01
Can confirm. Current source as of https://github.com/stepmania/stepmania/commit/76d07bca14bb4dc097616212a2c0cc946ded9470 fixed this issue. Thank you very much!
