### ISSUE TITLE
GTK modules missing while setup on Arch

### ISSUE THREAD

**Issue by ghost** [stepmania/stepmania#1893] opened 2019-09-14 15:01 UTC
/usr/include/pango-1.0/pango/pango-coverage.h:28:10: fatal error: hb.h: No such file or directory
   28 | #include <hb.h>
      |          ^~~~~~
compilation terminated.
make[2]: *** [src/CMakeFiles/GtkModule.dir/build.make:63: src/CMakeFiles/GtkModule.dir/arch/LoadingWindow/LoadingWindow_GtkModule.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:350: src/CMakeFiles/GtkModule.dir/all] Error 2
make: *** [Makefile:152: all] Error 2

**Comment by mkroening** [comment] 2019-09-14 15:02
Duplicate of  #1850.

Edit: I'm also reworking the [stepmania-git](https://aur.archlinux.org/packages/stepmania-git/) package with workarounds for this.

**Comment by ghost** [comment] 2019-09-14 15:33
> Duplicate of #1850.
> 
> Edit: I'm also reworking the [stepmania-git](https://aur.archlinux.org/packages/stepmania-git/) package with workarounds for this.

Oh, sorry then can you reply this issue when you finish your rework.

**Comment by mkroening** [comment] 2019-09-16 14:28
I just updated the package.

See [0001-GtkModule-Add-harfbuzz-dependency.patch](https://aur.archlinux.org/cgit/aur.git/tree/0001-GtkModule-Add-harfbuzz-dependency.patch?h=stepmania-git) as workaround for this specific problem.

**Comment by ghost** [comment] 2019-09-16 17:44
I am switched to debian 10 this is so good.

**Comment by mkroening** [comment] 2020-06-21 21:50
@quietly-turning, this can be closed.

**Comment by quietly-turning** [comment] 2020-06-21 22:38
Thanks for the heads up/reminder.

**Closed as completed** 2020-06-21 22:37 UTC
