### ISSUE TITLE
Stepmania Reset

### ISSUE THREAD

**Issue by WillamJSK8** [stepmania/stepmania#1309] opened 2016-10-09 00:13 UTC
How do your reset Stepmania, so that it goes back to its original screen.... (I have broke Stepmaina 5 using the Simply Love Theme.) All it shows now:

![20161008_170823 1](https://cloud.githubusercontent.com/assets/22718748/19216662/6cbbffec-8d7a-11e6-86f7-16d4aefe7792.jpg)

Even if it says press scroll lock, it will say everything is missing. Simply Love is not in my 'Themes' folder anymore

**Comment by kyzentun** [comment] 2016-10-09 00:16
Maybe you installed the theme wrong.  Is Themes/Simply Love/ a folder with metrics.ini, BGAnimations, and other files and folders in it?
If it's an empty folder, or everything is inside another folder inside it, that's what is wrong.

**Comment by WillamJSK8** [comment] 2016-10-09 00:19
I put it back in, and its not an empty folder, everythings inside it

**Comment by kyzentun** [comment] 2016-10-09 00:20
Do you have a "default" theme and "_fallback" theme in the Themes folder?

**Comment by WillamJSK8** [comment] 2016-10-09 00:21
yes

**Comment by kyzentun** [comment] 2016-10-09 00:42
Well, you can manually change the preference back in Preferences.ini (https://github.com/stepmania/stepmania/wiki/Manually-Changing-Preferences) for now.

I don't think Simply Love is actually the cause of the problem.  It seems like something went wrong in installing it or when changing themes.

**Comment by WillamJSK8** [comment] 2016-10-09 00:59
how do chage it back using Preferences.ini?

**Comment by WillamJSK8** [comment] 2016-10-09 01:00
excuse me for my spelling

**Comment by dguzek** [comment] 2016-10-09 01:00
Scroll to the bottom of Preferences.ini and change the line that probably reads

```
Theme=Simply Love
```

to

```
Theme=default
```

**Comment by WillamJSK8** [comment] 2016-10-09 01:01
let me see,,,

**Comment by WillamJSK8** [comment] 2016-10-09 01:07
It will just revert back to Simply Love again... What else do i do?

**Comment by dguzek** [comment] 2016-10-09 01:10
1. Quit StepMania.
2. Change the `Theme=default` line of your Preferences.ini file as described above.
3. re-open StepMania.  The default theme should now be enabled.

If this doesn't solve your problem, try uninstalling StepMania via the uninstall.exe in the main folder, and then reinstalling.

**Comment by WillamJSK8** [comment] 2016-10-09 01:13
Before, when i did this, I was uninstalling and reinstalling it over and over again, but keeps doing that screen over and over again

**Comment by dguzek** [comment] 2016-10-09 01:14
Do you have multiple installs of StepMania on your computer?

**Comment by WillamJSK8** [comment] 2016-10-09 01:14
no

**Comment by WillamJSK8** [comment] 2016-10-09 01:15
it would't let me do that anyway

**Comment by kyzentun** [comment] 2016-10-09 01:19
Is the stepmania.exe in the Program folder, or is it somewhere else?  Stepmania (unfortunately) relies heavily on where folders are relative to the exe.

Did you do something like make a copy of the exe and put the copy on your desktop?  A shortcut might work better (though I haven't used Windows in a very long time).

**Comment by WillamJSK8** [comment] 2016-10-09 01:20
It is a shortcut on desktop

**Comment by WillamJSK8** [comment] 2016-10-09 01:21
from the program folder

**Comment by dguzek** [comment] 2016-10-09 01:22
Out of curiosity, where do you have StepMania installed to?

**Comment by WillamJSK8** [comment] 2016-10-09 01:22
Program Files (x86)...

**Comment by dguzek** [comment] 2016-10-09 01:24
That will cause permission errors that cause all sorts of strange things to happen; maybe even this.  Uninstall one more time, and install to anywhere within your user folder, like your Desktop or Documents.

**Comment by kyzentun** [comment] 2016-10-09 01:25
Somebody needs to write some code to detect that and display a proper refusal to run when it occurs.

**Comment by dguzek** [comment] 2016-10-09 01:26
One of our many Windows devs, no doubt.

**Comment by WillamJSK8** [comment] 2016-10-09 01:34
I finally got it to work now

**Comment by dguzek** [comment] 2016-10-09 01:35
Cool. I'll close this issue now, then.

**Closed by dguzek** 2016-10-09 01:35 UTC

**Comment by shakesoda** [comment] 2016-10-09 06:33
@kyzentun anything that doesn't write into the game folder should work fine. windows users should just install content into `%APPDATA%/StepMania 5` (not the game folder, people need to stop thinking that's where content goes - we should probably just ship the default content smzip'd...)

that said, virtual store ruins everything, this is why the installer (used to?) defaults to `C:\Games`
