### ISSUE TITLE
Bugs Report

### ISSUE THREAD

**Issue by s0351060** [stepmania/stepmania#648] opened 2015-05-24 07:02 UTC
機型名稱：	iMac
  機型識別碼：	iMac12,2
  處理器名稱：	Intel Core i5
  處理器速度：	2.7 GHz
  處理器數目：	1
  總核心數目：	4
  L2 快取記憶體（每個核心）：	256 KB
  L3 快取記憶體：	6 MB
  記憶體：	8 GB
OSX Yosemite
StepMania5.0-git-b3addbe crash report (build 7, 20150331 @ 23:48:24 EDT)
--------------------------------------

Architecture:   Mac OS X (i386)
Crash reason:   Segmentation fault - address not mapped at 0x00000000
Crashed thread: Main thread

Checkpoints:
Thread: GUI thread
Thread: Main thread
        ScrollBar.cpp:97 
        GameSoundManager.cpp:557 1.046265, delta 0.015718
        ScrollBar.cpp:67 
        ScrollBar.cpp:85 
        ScrollBar.cpp:97 
Thread: Decode thread
        RageSoundDriver_Generic_Software.cpp:204 
        RageSoundDriver_Generic_Software.cpp:204 
        RageSoundDriver_Generic_Software.cpp:204 
        RageSoundDriver_Generic_Software.cpp:204 
        RageSoundDriver_Generic_Software.cpp:204 
Thread: Music thread
Thread: HAL I/O thread
Thread: Worker thread (MemoryCardWorker)
Thread: Worker thread (/@mc1int/)
Thread: Worker thread (/@mc2int/)
Thread: Input thread
Thread: Streaming sound buffering

Thread: Main thread
9ad9761e: CFDataGetBytePtr (CoreFoundation)
00609ab4: KeyCodeToChar(unsigned short, unsigned int) 
00609aea: KeyCodeToChar(unsigned short, unsigned int) 
00609a76: InputHandler_MacOSX_HID::DeviceButtonToChar(DeviceButton, bool) 
00354e58: RageInput::DeviceInputToChar(DeviceInput, bool) 
00527d51: ScreenSelectMusic::Input(InputEventPlus const&) 
005ab241: HandleInputEvents(float) 
005ab241: HandleInputEvents(float) 
005ab567: HandleInputEvents(float) 
00116938: GameLoop::RunGameLoop() 
005a9252: sm_main 
00621c7b: -[SMMain startGame:] 

Static log:
StepMania5.0-git-b3addbe
Compiled 20150331 @ 23:48:24 EDT (build 7)
Log starting 2015-05-24 14:54:34
Loading window: macosx
Model: iMac12,2 (4/4)
Clock speed 2.70 GHz
Mac OS X 10.10.3
Memory: 8.00 GB
Sound driver: AudioUnit
Lights driver: SystemMessage
Video renderers: 'opengl'
Paletted textures disabled: GL_EXT_paletted_texture missing.
OGL Vendor: ATI Technologies Inc.
OGL Renderer: ATI Radeon HD 6770M OpenGL Engine
OGL Version: 2.1 ATI-1.32.20
OGL Max texture size: 16384
OGL Texture units: 8
GLU Version: 1.3 MacOSX
OGL Extensions:
  GL_APPLE: aux_depth_stencil, client_storage, element_array, fence, float_pixels, flush_buffer_range, 
    flush_render, object_purgeable, packed_pixels, pixel_buffer, rgb_422, row_bytes, specular_vector, 
    texture_range, transform_hint, vertex_array_object, vertex_array_range, vertex_point_size, 
    vertex_program_evaluators, ycbcr_422
  GL_ARB: color_buffer_float, depth_buffer_float, depth_clamp, depth_texture, draw_buffers, 
    draw_elements_base_vertex, draw_instanced, fragment_program, fragment_program_shadow, fragment_shader, 
    framebuffer_object, framebuffer_sRGB, half_float_pixel, half_float_vertex, imaging, instanced_arrays, 
    multisample, multitexture, occlusion_query, pixel_buffer_object, point_parameters, point_sprite, 
    provoking_vertex, seamless_cube_map, shader_objects, shader_texture_lod, shading_language_100, shadow, 
    shadow_ambient, sync, texture_border_clamp, texture_compression, texture_compression_rgtc, texture_cube_map, 
    texture_env_add, texture_env_combine, texture_env_crossbar, texture_env_dot3, texture_float, 
    texture_mirrored_repeat, texture_non_power_of_two, texture_rectangle, texture_rg, transpose_matrix, 
    vertex_array_bgra, vertex_blend, vertex_buffer_object, vertex_program, vertex_shader, window_pos
  GL_ATI: blend_equation_separate, blend_weighted_minmax, separate_stencil, texture_compression_3dc, 
    texture_env_combine3, texture_float, texture_mirror_once
  GL_EXT: abgr, bgra, bindable_uniform, blend_color, blend_equation_separate, blend_func_separate, blend_minmax, 
    blend_subtract, clip_volume_hint, compiled_vertex_array, debug_label, debug_marker, draw_buffers2, 
    draw_range_elements, fog_coord, framebuffer_blit, framebuffer_multisample, framebuffer_object, 
    framebuffer_sRGB, geometry_shader4, gpu_program_parameters, gpu_shader4, multi_draw_arrays, 
    packed_depth_stencil, packed_float, provoking_vertex, rescale_normal, secondary_color, 
    separate_specular_color, shadow_funcs, stencil_two_side, stencil_wrap, texture_array, 
    texture_compression_dxt1, texture_compression_s3tc, texture_env_add, texture_filter_anisotropic, 
    texture_integer, texture_lod_bias, texture_mirror_clamp, texture_rectangle, texture_sRGB, texture_sRGB_decode, 
    texture_shared_exponent, timer_query, transform_feedback, vertex_array_bgra
  GL_IBM_rasterpos_clip
  GL_NV: blend_square, conditional_render, depth_clamp, fog_distance, light_max_exponent, texgen_reflection, 
    texture_barrier
  GL_SGIS: generate_mipmap, texture_edge_clamp, texture_lod
  GL_SGI_color_matrix
OpenGL Windowed 2560x1298 32 color 16 texture 60Hz Vsync SmoothLines
WARNING: Failed to add HID element with cookie 0x2 to queue: 3758097090
WARNING: Background missing: nanako.avi
Mixing underruns: 1
Players joined: P1
Top Screen: ScreenSelectMusic
Language: en
Current renderer: OpenGL
Theme: default

Partial log:
02:35.176: BannerCache::LoadCachedBanner(/Songs/Anime Songs/Nanako/nanakologo.png): Cache/Banners/Songs_Anime Songs_Nanako_nanakologo.png
02:35.176: Loading banner texture Cache/Banners/Songs_Anime Songs_Nanako_nanakologo.png; src 255x78; image 128x32
02:35.176: glTexImage2D (format GL_RGB5_A1, 128x32, format GL_BGRA, type GL_UNSIGNED_SHORT_1_5_5_5_REV, pixfmt 3, imgpixfmt 8)
02:35.177: Approximate sound time: driver frame 956889239, m_pImpl->m_Queue frame 2048..9728 (dist 26083), closest position is 9728
02:35.188: Zeroing this update.  Was 0.623741
02:35.291: glTexImage2D (format GL_RGBA8, 256x128, format GL_RGBA, type GL_UNSIGNED_BYTE, pixfmt 0, imgpixfmt 0)
02:35.291: RageBitmapTexture: Loaded '/Songs/Anime Songs/Nanako/nanakologo.png' (256x128); RGBA8 opaque, source 255,78;  image 255,78.
02:35.427: RageSound: Load "/Songs/Anime Songs/Nanako/NanakoEnding.mp3" (precache: 0)
02:35.427: Starting thread: Streaming sound buffering
02:35.427: Sound "/Songs/Anime Songs/Nanako/NanakoEnding.mp3" has a start time 0.000098 seconds in the past

-- End of report

**Comment by kyzentun** [comment] 2015-06-03 21:38
This looks like a duplicate of #504, which was fixed in April.

**Closed by kyzentun** 2015-06-03 21:38 UTC
Labels: duplicate

**Comment by s0351060** [comment] 2015-06-04 01:21
THX
> Kyzentun <notifications@github.com> 於 2015年6月4日 上午5:38 寫道：
> 
> #504 <https://github.com/stepmania/stepmania/issues/504>

**Comment by s0351060** [comment] 2015-06-04 01:28
the crash occurs after updating to OS X Yosemite
> chuncat123 <chuncat123@gmail.com> 於 2015年6月4日 上午9:21 寫道：
> 
> THX
>> Kyzentun <notifications@github.com <mailto:notifications@github.com>> 於 2015年6月4日 上午5:38 寫道：
>> 
>> #504 <https://github.com/stepmania/stepmania/issues/504>
