### ISSUE TITLE
"StepMania-5.1.0-b2-mac can't be mounted because there are no mountable file systems"

### ISSUE THREAD

**Issue by 1FireXY1** [stepmania/stepmania#1824] opened 2019-05-06 00:11 UTC
When I tried to open the dmg file, it says there are no mountable file systems. If it helps my Mac is on version 10.11.6 OS X El Captain.

**Comment by dguzek** [comment] 2019-05-06 05:40
Duplicate of #1726.

**Closed by dguzek** 2019-05-06 05:40 UTC
Labels: macOS
