### ISSUE TITLE
MinTNSToHideNotes issue

### ISSUE THREAD

**Issue by sangyeolbaek** [stepmania/stepmania#1816] opened 2019-04-08 02:13 UTC
I had tried playing ECFA mode with Simply Love theme running, and i noticed a little problem.

so with sm5.1, whenever i get a GREAT, which would be TapNoteScore_W4, the note would just pass through the targets without disappearing, even though in the scripts, for ECFA the MinTNSToHideNotes was set to TapNoteScore_W4. Not a huge problem, but it always throws me off

this problem does not happen when playing with sm5.0.12, as getting a GREAT in ECFA properly makes the note disappear

so i figured there must be an issue with rendering the MinTNSToHideNotes in the Stepmania engine, not the theme's issue

anyone encounter this issue?

**Comment by RodentVienna** [comment] 2019-04-08 06:41
same for me. thank you for reporting this, i wouldn't have by far found better descriptive words.

**Comment by ianklatzco** [comment] 2019-04-09 04:26
interesting, i didn’t know there was a setting to pick when notes would disappear. 

it’s even more interesting that 5.0.12 -> 5.1 introduced a bug that broke the setting....

**Comment by sangyeolbaek** [comment] 2019-04-09 22:18
For Simply Love, you can see it in Scripts/SL_Init.lua

**Comment by dguzek** [comment] 2019-04-26 19:42
There is a bug lurking here, but the original description (above) is somewhat off.

# About

Setting `MinTNSToHideNotes` via `PREFSMAN:SetPreference()` doesn't bring about the desired effect consistently.

# Background

The Simply Love for SM5 theme allows players to switch between "gamemodes" on the fly.  Players choose one of four options (_Casual_, _Competitive_, _ECFA_, or _StomperZ_) on [ScreenSelectPlayMode](https://github.com/teejusb/Simply-Love-SM5/blob/2690365fb82411981400be9c1c4513b3e13eb8d6/metrics.ini#L188-L221), which is [stored as a string](https://github.com/teejusb/Simply-Love-SM5/blob/2690365fb82411981400be9c1c4513b3e13eb8d6/BGAnimations/ScreenSelectPlayMode%20underlay/default.lua#L52-L55) in `SL.Global.GameMode` during the `OffComand` of ScreenSelectPlayMode.  The value of `SL.Global.GameMode` is then relied upon extensively throughout the theme to present the player with content unique to the gamemode chosen (unique screens, flow, onscreen text, etc.).

Some of these differences between gamemodes are accomplished by changing global StepMania Preferences using `PREFSMAN:SetPreference()`.   In Simply Love for SM5, this is accomplished in `SetGameModePreferences()` which [is called](https://github.com/teejusb/Simply-Love-SM5/blob/2690365fb82411981400be9c1c4513b3e13eb8d6/BGAnimations/ScreenSelectPlayMode%20underlay/default.lua#L57-L58) in the same `OffCommand` immediately after `SL.Global.GameMode` is set.

The [relevant part](https://github.com/teejusb/Simply-Love-SM5/blob/2690365fb82411981400be9c1c4513b3e13eb8d6/Scripts/SL-Helpers.lua#L124-L126) of `SetGameModePreferences()` loops through a table of [hard-coded Preferences](https://github.com/teejusb/Simply-Love-SM5/blob/2690365fb82411981400be9c1c4513b3e13eb8d6/Scripts/SL_Init.lua#L181-L196) associated with the newly chosen gamemode and sets them using `PREFSMAN:SetPreference()`.

This all occurs prior to getting to ScreenSelectMusic for the first time.

# Debugging/Testing

Empirical testing on ScreenGameplay using `PREFSMAN:GetPreference()` suggests that all the Preferences that should be changed are correctly set.  For example, adding this line to the top of *./BGAnimations/ScreenGameplay overlay/default.lua*

```lua
SM( PREFSMAN:GetPreference("MinTNSToHideNotes") )
```

will cause the value for `MinTNSToHideNotes` to display via SystemMessage at the start of ScreenGameplay.  For `MinTNSToHideNotes`, and all other Preferences I tested, this always reports correctly, regardless of what demonstrably occurs.  

So, calling `SM( PREFSMAN:GetPreference("MinTNSToHideNotes") )` in *Competitive* mode will always show `TapNoteScore_W3` and calling it in *ECFA* mode will always show `TapNoteScore_W4`, as is expected.

# The Bug

The problem is that the value of `MinTNSToHideNotes` appears to be inconsistently applied or respected (or something).  My testing went like this:

1. start SM5 with SL already selected as the theme
2. start a new game; choose *ECFA*
3. proceed to gameplay; gameplay respects `MinTNSToHideNotes` appropriately; W4 judgments are hidden
4. back out of this game cycle
5. start a new game; choose *Competitive*
6. proceed to gameplay; gameplay will report the correct value for `MinTNSToHideNotes` via `Trace()` but not actually respect it; gameplay will behave as though we're still in *ECFA* hiding W4 judgments when it should now stop at W3
7. back out of this game cycle
8. start a new game; choose *Competitive* again
9. proceed to gameplay; now gameplay behaves correctly

From my testing, it seems that `MinTNSToHideNotes` is always respected properly for the first game cycle regardless of which gamemode is chosen by the player.  If the gamemode is subsequently changed, the new value of `MinTNSToHideNotes` will demonstrably lag behind for one game cycle, despite `PREFSMAN:GetPreference()` reporting the correct, updated value.

The underlying problematic behavior, that `MinTNSToHideNotes` isn't immediately respected in ScreenGameplay, can be recreated using any combination of gamemodes in Simply Love.  It is not limited to ECFA and Competitive.

## Important Notes

This has nothing to do with SM5.0.12 vs SM5.1 as I recreated the bug in both using identical copies of SL.  

It also appears to be specific to `MinTNSToHideNotes` (thank goodness); I played around with other Preferences that are manipulated by SL such as `RegenComboAfterMiss` and those were each applied in gameplay appropriately.

Unfortunately, I cannot definitively say that this only occurs with `MinTNSToHideNotes` as I don't fully understand the bug.

---

### Aside

For the record, I have never been keen on themes changing global Preferences.  Preferences persist between themes, SL changes preferences constantly and silently, most players are completely unaware that this is occurring, and explaining all this is complicated.

I believe that players shouldn't need to understand what is occurring behind the scenes in the theme/engine to play the game, but by changing preferences non-transparently, SL has put players who want to switch away from SL in confusing scenarios again and again.  It is frustrating for players and developers alike.

**Comment by dguzek** [comment] 2019-05-22 23:41
@sangyeolbaek – Has this issue been resolved in Simply Love 4.8.3?

**Comment by sangyeolbaek** [comment] 2019-05-23 09:59
I tested it out on SM5.1, and it works properly now.

Thanx for the your hard work!

**Closed** 2019-05-23 10:00 UTC
