### ISSUE TITLE
Keeps crashing on mac

### ISSUE THREAD

**Issue by thepaperwings** [stepmania/stepmania#572] opened 2015-04-24 04:00 UTC
Hi, it's my first time posting here so sorry if I didn't do it correctly but stepmania keeps crashing on my macbook OS X YOSEMITE 2.3 GHz Intel Core i7, and here is the crashlog. Thank you.

StepMania5.0-git-b3addbe crash report (build 7, 20150331 @ 23:48:24 EDT)
--------------------------------------

Architecture:   Mac OS X (i386)
Crash reason:   Segmentation fault - address not mapped at 0x00000000
Crashed thread: Main thread

Checkpoints:
Thread: GUI thread
Thread: Main thread
        ScrollBar.cpp:85 
        ScrollBar.cpp:97 
        ScrollBar.cpp:67 
        ScrollBar.cpp:85 
        ScrollBar.cpp:97 
Thread: Decode thread
        RageSoundDriver_Generic_Software.cpp:204 
        RageSoundDriver_Generic_Software.cpp:204 
        RageSoundDriver_Generic_Software.cpp:204 
        RageSoundDriver_Generic_Software.cpp:204 
        RageSoundDriver_Generic_Software.cpp:204 
Thread: Music thread
Thread: HAL I/O thread
Thread: Worker thread (MemoryCardWorker)
Thread: Worker thread (/@mc1int/)
Thread: Worker thread (/@mc2int/)
Thread: Input thread
Thread: Streaming sound buffering

Thread: Main thread
961a710e: CFDataGetBytePtr (CoreFoundation)
00609ab4: KeyCodeToChar(unsigned short, unsigned int) 
00609aea: KeyCodeToChar(unsigned short, unsigned int) 
00609a76: InputHandler_MacOSX_HID::DeviceButtonToChar(DeviceButton, bool) 
00354e58: RageInput::DeviceInputToChar(DeviceInput, bool) 
00527d51: ScreenSelectMusic::Input(InputEventPlus const&) 
005ab567: HandleInputEvents(float) 
00116938: GameLoop::RunGameLoop() 
005a9252: sm_main 
00621c7b: -[SMMain startGame:] 

Static log:
StepMania5.0-git-b3addbe
Compiled 20150331 @ 23:48:24 EDT (build 7)
Log starting 2015-04-23 20:57:06
Loading window: macosx
Model: MacBookPro9,1 (8/8)
Clock speed 2.30 GHz
Mac OS X 10.10.1
Memory: 4.00 GB
Sound driver: AudioUnit
Lights driver: SystemMessage
Video renderers: 'opengl'
Paletted textures disabled: GL_EXT_paletted_texture missing.
OGL Vendor: NVIDIA Corporation
OGL Renderer: NVIDIA GeForce GT 650M OpenGL Engine
OGL Version: 2.1 NVIDIA-10.0.43 310.41.05f01
OGL Max texture size: 16384
OGL Texture units: 8
GLU Version: 1.3 MacOSX
OGL Extensions:
  GL_APPLE: aux_depth_stencil, client_storage, element_array, fence, float_pixels, flush_buffer_range, 
    flush_render, object_purgeable, packed_pixels, pixel_buffer, rgb_422, row_bytes, specular_vector, 
    texture_range, transform_hint, vertex_array_object, vertex_array_range, vertex_point_size, 
    vertex_program_evaluators, ycbcr_422
  GL_ARB: color_buffer_float, depth_buffer_float, depth_clamp, depth_texture, draw_buffers, 
    draw_elements_base_vertex, draw_instanced, fragment_program, fragment_program_shadow, fragment_shader, 
    framebuffer_object, framebuffer_sRGB, half_float_pixel, half_float_vertex, imaging, instanced_arrays, 
    multisample, multitexture, occlusion_query, pixel_buffer_object, point_parameters, point_sprite, 
    provoking_vertex, seamless_cube_map, shader_objects, shader_texture_lod, shading_language_100, shadow, sync, 
    texture_border_clamp, texture_compression, texture_compression_rgtc, texture_cube_map, texture_env_add, 
    texture_env_combine, texture_env_crossbar, texture_env_dot3, texture_float, texture_mirrored_repeat, 
    texture_non_power_of_two, texture_rectangle, texture_rg, transpose_matrix, vertex_array_bgra, vertex_blend, 
    vertex_buffer_object, vertex_program, vertex_shader, window_pos
  GL_ATI: separate_stencil, texture_env_combine3, texture_float, texture_mirror_once
  GL_EXT: abgr, bgra, bindable_uniform, blend_color, blend_equation_separate, blend_func_separate, blend_minmax, 
    blend_subtract, clip_volume_hint, compiled_vertex_array, debug_label, debug_marker, depth_bounds_test, 
    draw_buffers2, draw_range_elements, fog_coord, framebuffer_blit, framebuffer_multisample, 
    framebuffer_multisample_blit_scaled, framebuffer_object, framebuffer_sRGB, geometry_shader4, 
    gpu_program_parameters, gpu_shader4, multi_draw_arrays, packed_depth_stencil, packed_float, provoking_vertex, 
    rescale_normal, secondary_color, separate_specular_color, shadow_funcs, stencil_two_side, stencil_wrap, 
    texture_array, texture_compression_dxt1, texture_compression_s3tc, texture_env_add, 
    texture_filter_anisotropic, texture_integer, texture_lod_bias, texture_mirror_clamp, texture_rectangle, 
    texture_sRGB, texture_sRGB_decode, texture_shared_exponent, timer_query, transform_feedback, 
    vertex_array_bgra
  GL_IBM_rasterpos_clip
  GL_NV: blend_square, conditional_render, depth_clamp, fog_distance, fragment_program2, fragment_program_option, 
    light_max_exponent, multisample_filter_hint, point_sprite, texgen_reflection, texture_barrier, 
    vertex_program2_option, vertex_program3
  GL_SGIS: generate_mipmap, texture_edge_clamp, texture_lod
OpenGL Windowed 854x480 32 color 16 texture 60Hz Vsync SmoothLines
WARNING: Couldn't initialize device.
Mixing underruns: 1
Players joined: P1
Top Screen: ScreenSelectMusic
Language: en
Current renderer: OpenGL
Theme: default

Partial log:
00:21.025: RageTextureManager: deleting '/Themes/default/Fonts/_open sans semibold 48px [main-stroke] 15x15.png'.
00:21.026: RageTextureManager: deleting '/Themes/default/Graphics/ScreenSelectPlayMode Icon/_background base (dither).png'.
00:21.026: ScreenSelect::~ScreenSelect()
00:21.026: Performing texture garbage collection.
00:21.026: Zeroing this update.  Was 0.313798
00:21.142: glTexImage2D (format GL_RGBA8, 512x256, format GL_RGBA, type GL_UNSIGNED_BYTE, pixfmt 0, imgpixfmt 0)
00:21.142: RageBitmapTexture: Loaded '/Songs/Anime Trance Pack/Agape/a_bn.png' (512x256); RGBA8 opaque, source 418,164;  image 418,164.
00:21.269: RageSound: Load "/Songs/Anime Trance Pack/Agape/Agape.ogg" (precache: 0)
00:21.269: Starting thread: Streaming sound buffering
00:21.270: Sound "/Songs/Anime Trance Pack/Agape/Agape.ogg" has a start time 0.001010 seconds in the past

-- End of report

**Comment by kyzentun** [comment] 2015-04-24 04:33
This looks like a duplicate of #504, which was fixed after the last release.

**Comment by kyzentun** [comment] 2015-06-25 18:19
Closing because there has been a release with the fix now.

**Closed by kyzentun** 2015-06-25 18:19 UTC
Labels: duplicate
