### ISSUE TITLE
[5.1-git] Attacks (AKA Course Mods) not being read.

### ISSUE THREAD

**Issue by MrThatKid** [stepmania/stepmania#1107] opened 2016-05-16 20:29 UTC
In 5.0, .ssc files have a "#ATTACK" section. This can be placed at the top, meaning all charts have the attacks, or under a specific chart, with that one having the attacks.
In 5.1, this isn't being read, leading to that chart (or all charts) not having its' attacks launched at all.
Mods done using LUA (not "#ATTACKS" or Course crs files) seem to fire off as intended.

However, .crs files exhibit the same problem. No attacks are launched, even if there are attacks mentioned. (This might be what YungDaVinci was reporting.)
StepMania5.1-git-21f924d
Compiled 20160516 @ 15:38:56 (build 21f924d)
Ubuntu 16.04 64-bit

**Comment by kyzentun** [comment] 2016-05-16 20:32
This is a duplicate of #1103.

**Closed by kyzentun** 2016-05-16 20:32 UTC
Labels: duplicate
