### ISSUE TITLE
HighScores for Edits steps

### ISSUE THREAD

**Issue by xmaxthemer** [stepmania/stepmania#677] opened 2015-06-10 04:34 UTC
Hi to everyone. I noticed that the high scores for edits steps are not being displayed in select music unless you first select the chart, start gameplay and then return to select music screen. Any idea of why is this happening? Thanks!

**Comment by shakesoda** [comment] 2015-06-10 04:37
It's intentional that scores are not stored for edits, since the idea is that they can be loaded from user profiles/flash drives and are not standard charts.

It's a very old behavior that may be worth changing, though.

**Comment by kyzentun** [comment] 2015-06-10 04:37
This is a duplicate of #550.  Update to 5.0.8 and scores should show up fine, at least for edits not loaded from the profile.

**Comment by shakesoda** [comment] 2015-06-10 04:38
oh, looks like I'm behind the times already. woops.

**Closed by kyzentun** 2015-06-10 04:37 UTC
Labels: misfeature

**Comment by xmaxthemer** [comment] 2015-06-10 15:57
Nice! Thanks for the answers and the fix of the problem.
