### ISSUE TITLE
[SM5.1_new, WinXP] everything froze in gameplay after 3-5 sets of game.

### ISSUE THREAD

**Issue by sillybear** [stepmania/stepmania#1459] opened 2017-05-26 16:35 UTC
It's been confirmed via DDR+ITG fb group by 3 people (including me). We all have to restart the program to get rid of the problem. Just play until you reach between 3 to 5 sets of games and when you reach gameplay, everything froze. Though it does not happen to non-XP users.

**Comment by sillybear** [comment] 2017-05-26 16:44
![untitled-2](https://cloud.githubusercontent.com/assets/6451629/26504075/ae72f5ca-4275-11e7-9a44-b9ea08fa2aaa.png)

**Comment by chrispable** [comment] 2017-05-26 19:04
your not putting any information that can identify the issue. what git tag did you compile. what was the latest git tag that worked prior to the freeze. describe the freeze in detail. post logs. what are your pc specs. driver versions, etc. the same to anyone else complaining of the issue. I've not experienced a full on freeze myself.

**Comment by sillybear** [comment] 2017-05-26 22:50
this was the last commit before I compiled it and shared with everyone. In my case it was already there since last year and I all I thought was it's my video card issue to SM5. I only confirmed it when others experienced it too.

https://github.com/stepmania/stepmania/commit/41b602c90ff8fc4c571578bd3a5d9b21a41b131d

**Comment by chrispable** [comment] 2017-05-27 03:33
I've run it on XP and don't have the problem you describe. There is not enough information to go on from what your providing. The commit you reference has zero bearing on any part of the program too. It's for future feature development.

Logs might help. Finding exact computer specs and driver versions of all involved looking for correlation. D3d/ogl, etc. Better yet, if your skilled enough to compile, track down the commit that causes the problem for you.

**Comment by JJKallday** [comment] 2017-07-07 18:37
Bumping this because I'm still dealing with this problem as well. The game will work fine for awhile before the arrows will just stop scrolling during the middle of a song. Once this happens, every song becomes broken until a restart is done. I took this video of the problem in action: https://drive.google.com/open?id=0B_S4QKNQyNInNmxWTkpFb1dTSms

My specs are an Optiplex 745 with an ATI Radeon 3450 running Windows XP. I'd be happy to share logs if someone could tell me where they're stored.

**Comment by dguzek** [comment] 2017-07-07 18:47
@JJKallday – I don't use Windows, myself, but [the Wiki suggests](https://github.com/stepmania/stepmania/wiki/User-Data-Locations) that your logs will be located at
`%APPDATA%\StepMania 5\Logs`.

If not there, try `%APPDATA%\StepMania 5.1\Logs\`.

**Comment by JJKallday** [comment] 2017-07-07 19:01
@dguzek My monitor is a trisync actually. I'm tied to XP because it is the ideal OS for running arcade data.

I do have a Lubuntu partition on the same system, but I have a whole host of other problems with that setup. (Lights not working, timing being a lot worse than the XP build). If not for this freezing issue, the XP build would be perfect for me.

**Comment by chrispable** [comment] 2017-07-07 21:14
Is this xp embedded? Is ewf in play here? If so it may have more to do with paging than a program bug.

**Comment by JJKallday** [comment] 2017-07-16 01:10
It's a build of WinXP called MicroXP. I don't know what EWF is.

**Comment by FishamanP** [comment] 2017-10-11 23:57
Adding that this issue still persists, and contrary to the initial report it DOES happen on other operating systems, albeit orders of magnitude more rarely. 5.0.12 official download, W10, Nvidia GTX 850M forced on with Optimus.

On my XPE machine (HD 3450, EWF on) it happens almost entirely predictably, based on how long Stepmania has been open. If the program is exited and restarted before this occurs, the "timer" for it to happen is reset. Once it does occur, results have been inconsistent. Sometimes it would persist across program restarts, other times if I waited long enough with Stepmania closed it would be just fine.

**Comment by Flameshadowxeroshin** [comment] 2017-10-12 17:30
@FishamanP and @sillybear, could you get people to look at what SM audio driver people are using? that’s obviously where the problem is. if audio on your entire computer is borked, though, that honestly suggests a bug in the sound chip drivers

**Comment by FishamanP** [comment] 2017-10-16 17:19
XPE machine is using WaveOut, audio did not bork.
W10 machine is using the default driver on that platform (DirectSound?), audio borked. Like you said, SM shouldn't have any effects on sound once closed down, so it probably is an audio driver bug. But the fact that it's triggering a driver bug may point to the fact Stepmania is invoking undefined behavior or something to that effect. Does any game state depend on audio processing?

I should also clarify that on both platforms, despite the video (if present) glitching and the arrows stopping/shaking/skipping, the audio plays perfectly normally, with no glitches even when everything else burns down. If the chart plays to its normal end, the game continues to results and then song select as normal, save for the bug instantly retriggering upon selecting any song.

**Comment by Flameshadowxeroshin** [comment] 2017-10-18 06:08
StepMania derives the current song position from what the audio driver claims it is for most drivers. Unfortunately this is pretty unreliable.

**Comment by chrispable** [comment] 2018-04-23 13:10
Some updates for tracking this issue -- I built a binary on a windows10 machine, I am getting low cpu usage (ie not maxing out a core) when I run the game. Low CPU usage seems to be the norm whether or not the game has focus on Windows 10. This is good for modern OSes. I took the exact same binary to an xp laptop.

With the game in focus, the entire core is maxed out. Out of focus, half of the core is in use. So this is looking like an update to the threading or maybe thread sleep logic may have caused that issue at least. I am going to attempt to track down which threads are maxing this out. I have a strong gut feeling the arrow lockup is directly related to this.

**Comment by chrispable** [comment] 2018-04-23 16:45
OK! I managed to get an xp laptop to exhibit the problem. I've attached a logfile. To get it, I setup sm5.1 to event mode, turned on the menu timer and auto play and just let it play the most difficult version of shiokara from mute sims x on loop over and over. I noticed it tends to be easier to encounter on songs with stops and bpm changes. Eventually, the problem manifested itself. Interestingly enough, it can actually recover when focus is LOST! (This is because when focus is lost, a sleep is put into the gfx pipeline if I recall). I intentionally left this on opengl to max out the cpu core to hopefully force the issue to appear.

This also makes me think the problem is NOT limited to windows xp, but rather, lower end hardware. It just so happens that lower end hardware tends to run windows xp. This machine is a mere dual core with a crappy quadro graphics card. I have an identical model with windows 7 and ubuntu my friend has I can try later (Dell precision M4400) to verify. Maybe it has something to do with threading priorities and the scheduler in use. If everyone else who is having this issue can publish detailed specs (processor, ram, gfx card and audio chipset OR post a log) that would help in finding a correlation.

As it stands, we have to find out what the reason is for the explosive cpu usage on these machines is and that should let the other threads actually breath and function correctly. I guess I can start by comparing the treading logic to that of OITG. I will also try switching the render to d3d on this machine and doing a burn test again to see if the issue occurs since d3d does NOT explode the cpu. 

[Copy of log.txt](https://github.com/stepmania/stepmania/files/1939165/Copy.of.log.txt)

**Comment by FishamanP** [comment] 2018-04-23 16:50
This issue isn't limited to XP, several people have reported it on Windows 10.

Happens regularly on XP with Direct3D, ATI Radeon HD 3450/2GB RAM/C2D E6300.
Happens extremely rarely on OpenGL, Nvidia GTX 850M/8GB RAM/Core i7 4700HQ (!!).

**Comment by chrispable** [comment] 2018-04-23 16:54
@FishamanP can you run this windowed on your xp build with processhacker ( https://processhacker.sourceforge.io/downloads.php ) (or taskmanager) in the background and monitor cpu usage. When it happens, can you give process hacker / task manager focus and report cpu usage before and after as well as if it recovers when focus is lost? I can compile you the latest version from git if you want, but the version you currently have should be sufficient to see this.

**Comment by FishamanP** [comment] 2018-04-23 16:56
Unfortunately it will be a few weeks at the earliest before I can, I live away from where my cabinet is with no transportation.

**Comment by chrispable** [comment] 2018-04-23 17:04
Better than nothing, as you seem to be the only other person who is actually contributing evidence and giving data points. I'll wait for that data from someone to confirm and head down the rabbit hole of the threading mess.

**Comment by chrispable** [comment] 2018-04-23 17:50
I got the issue to happen with d3d and forcing affinity to one core, log attached:
[log.txt](https://github.com/stepmania/stepmania/files/1939412/log.txt)

Another solution may be to get the difference into the song, calculate the difference, when an underrun is detected, reset the last seen value to zero maintaining a third counter thats used as a cursor?

**Comment by coderjo** [comment] 2018-04-23 19:43
btw, DWORD is an unsigned 32 bit integer.

**Comment by chrispable** [comment] 2018-04-23 19:50
Color me shocked, I saw the definition as:
typedef unsigned long DWORD, *PDWORD, *LPDWORD; 

Thanks for the clarification, at least we finally tracked down the bug!

**Comment by chrispable** [comment] 2018-04-24 16:04
Patch attached for others to test before I do a PR. Should merge fine with master and 5_1-new.

Note that by default this will do NOTHING. If you want ANY benefit from this, you need to look at your log file. Everyone's system will be different. On the 3 systems I tested with, it worked fine with setting this in preferences.ini:
RageSoundSampleCountClamp=134217728

This value also seems true for the audio chip on official DDR Motherboards and Optiplex 745s (Same audio chip).

Additionally, this will do NOTHING for you if you do not put it in the CORRECT preferences.ini. On windows, it is located under the sm folder in %appdata%. If you cant find the log, you can't find the preferences file.

[0001-Fix-for-audio-drivers-with-small-sample-count-limit.zip](https://github.com/stepmania/stepmania/files/1943586/0001-Fix-for-audio-drivers-with-small-sample-count-limit.zip)

**Comment by FishamanP** [comment] 2018-05-01 09:02
I have a rare opportunity to get to my cabinet soon. Could I get you to compile this against the latest 5.1-new, so I can test this?

**Comment by chrispable** [comment] 2018-05-01 11:33
I don't have a build that's exactly vanilla readily available. It's got a bunch of stuff I'm including for a customized build with the fix included. You'll need the 2013 msvc installed to use it.

Shoot me your email and we'll talk. I don't want this build in the wild yet because it has many other changes I haven't vetted for prime time yet.

**Comment by sillybear** [comment] 2018-05-03 11:06
@chrispable can you give me a hint in a log file for RageSoundSampleCountClamp to be set in prefs.ini? I'm gonna test it tomorrow.

**Comment by chrispable** [comment] 2018-05-03 11:27
Keep it at zero. Run it until you have the problem. Then look at the log. A hint will be in your log for your specific sound card driver. I can't tell you what your driver's value will be.  The code will try to guess (it assumes the clamp is a ceiling to the power of 2 of the highest value it sees.

**Comment by sillybear** [comment] 2018-05-03 13:00
I just tried running SM5.1 with your patch using VirtualBox with WinXP. Right after the problem appear, I opened the log file to see what you told me about. Is this what you were referring to (for example below)?

50:53.191: RageSoundDriver: driver returned a lesser position (311122 < 134217610). If this is a recurrent driver problem with your sound card and not an underrun, try setting the preference RageSoundSampleCountClamp to 134217728

**Comment by chrispable** [comment] 2018-05-03 14:05
Yes that is it exactly. So use the value it reported (134217728) as the value of the preference and the problem should go away.

**Comment by chrispable** [comment] 2018-05-03 14:35
Glad it worked, but we absolutely do NOT want this to be the default behavior (the user really SHOULD check the log for their value, but if they cannot, then I guess 2^27 is a good default suggestion). This is a fix for sound drivers that have a small sample limit. By using it, you cannot use the default buffer underrun code. It should remain as an option for people with a sound driver that limits their maximum sample count (which apparently affects windows 10 as well to this day). If you want to make a PR with this fix, go right ahead. I'm working on a few other patches and my local branch is kinda a mess right now.

**Comment by chrispable** [comment] 2018-05-05 01:11
Umm I encountered an issue. Some audio driver's have an issue with direct sound (because of the driver issue actually!) So if this happens with direct sound, it may mess up the audio for the whole computer until restarted. The arrows will render fine but audio will be messed up. The solution is to use waveout here. Note this can happen on Windows 10 as well if the audio driver has a small sample count limit. So keep that in mind!

**Comment by chrispable** [comment] 2018-05-07 12:50
waveout works just fine on windows 10. directsound will have a similar issue is what I am saying, it will get the sample count from the sound driver and when the count rolls over directsound itself (not stepmania) may have underrun code that will kick in and things will get really awkward. I believe the OS uses directsound for output which is why some users reported they needed to reboot after the issue with the arrows happened to fix the audio. The best method of handling this for drivers that may encounter this problem is to use waveout is all that I am saying (the fix will work in stepmania regardless of sound driver, I'm merely commenting the issue goes deeper than stepmania itself for programs that handle audio this way).

**Comment by FishamanP** [comment] 2018-05-21 05:19
@chrispable When you find some time, myself (and many others) are eagerly awaiting a fully working patch set!

**Comment by chrispable** [comment] 2018-05-24 18:31
Untangled this patch and posted it as a PR. It's in the hands of the repository admins now. A few other changes depend on the gameloop tweak here. If they accept this, I'll post them too.

**Comment by shakesoda** [comment] 2018-08-02 15:31
Merged the PR, closing. Sorry for such a long delay on reviewing it!

**Closed by shakesoda** 2018-08-02 15:31 UTC
