### ISSUE TITLE
Nightly build 844 -> SMO -> Pad crashes picking difficulty.

### ISSUE THREAD

**Issue by SpoOkyMagician** [stepmania/stepmania#279] opened 2014-08-30 20:53 UTC
I was trying to play on pad online and I noticed the game crashed after trying to change difficulty. I also noticed, player options does not register buttons with pad. I had to use keyboard... Worked before.
## StepMania v5.0 beta 3 crash report (build 26, 20140829 @ 11:19:38 Eastern Daylight Time)

Crash reason: Access Violation

Thread: Main thread
        ScrollBar.cpp:85 
        ScrollBar.cpp:97 
        ScrollBar.cpp:67 
        ScrollBar.cpp:85 
        ScrollBar.cpp:97 
Thread: Decode thread
        RageSoundDriver_Generic_Software.cpp:204 
        RageSoundDriver_Generic_Software.cpp:204 
        RageSoundDriver_Generic_Software.cpp:204 
        RageSoundDriver_Generic_Software.cpp:204 
        RageSoundDriver_Generic_Software.cpp:204 
Thread: Mixer thread
Thread: Music thread
        RageFileDriverDirectHelpers.cpp:227 C:/Users/Jeremy/Desktop/StepMania5-844-2014-08-29_11-18-10/Themes/*
        RageFileDriverDirectHelpers.cpp:227 C:/Users/Jeremy/Desktop/StepMania5-844-2014-08-29_11-18-10/Themes/default/Sounds/*
        RageFileDriverDirectHelpers.cpp:227 C:/Users/Jeremy/Desktop/StepMania5-844-2014-08-29_11-18-10/Themes/default/*
        RageFileDriverDirectHelpers.cpp:227 C:/Users/Jeremy/Desktop/StepMania5-844-2014-08-29_11-18-10/Themes/default/Sounds/default/*
        GameSoundManager.cpp:356 
Thread: Worker thread (MemoryCardWorker)
Thread: Worker thread (/@mc1int/)
Thread: Worker thread (/@mc2int/)
Thread: DirectInput thread
        InputHandler_DirectInput.cpp:755 
        InputHandler_DirectInput.cpp:731 
        InputHandler_DirectInput.cpp:750 
        InputHandler_DirectInput.cpp:755 
        InputHandler_DirectInput.cpp:731 
Thread: Streaming sound buffering

005cf4d6: void StepsDisplay::SetInternal(struct StepsDisplay::SetParams const &) [00400000+1cefc0+516]
75223c1b: MSVCR90!free [751c0000+63b4e+cd]
75223c3a: MSVCR90!free [751c0000+63b4e+ec]
732f5ec4: MSVCP90!std::basic_string<char,std::char_traits<char>,std::allocator<char> >::~basic_string<char,std::char_traits<char>,std::allocator<char> > [732f0000+5ebb+9]
005d5b5b: class XNode \* \* std::vector<class XNode *,class std::allocator<class XNode *> >::_Umove<class XNode * *>(class XNode \* *,class XNode \* *,class XNode \* *) [00400000+1d5b30+2b]
005cf8b8: void StepsDisplay::SetFromSteps(class Steps const *) [00400000+1cf850+68]
0048be20: void ScreenNetSelectMusic::UpdateDifficulties(enum PlayerNumber) [00400000+8bd50+d0]
0048c692: bool ScreenNetSelectMusic::MenuDown(class InputEventPlus const &) [00400000+8c540+152]
732f5e43: MSVCP90!std::basic_string<char,std::char_traits<char>,std::allocator<char> >::_Tidy [732f0000+5dfb+48]
0048912c: bool ScreenNetSelectBase::Input(class InputEventPlus const &) [00400000+89020+10c]
00489266: bool ScreenNetSelectBase::Input(class InputEventPlus const &) [00400000+89020+246]
0048ba1c: bool ScreenNetSelectMusic::Input(class InputEventPlus const &) [00400000+8b810+20c]
0059fb9b: void HandleInputEvents(float) [00400000+19f880+31b]
770014ad: kernel32!HeapFree [76ff0000+11499+14]
0059c9f9: void GameLoop::RunGameLoop(void) [00400000+19c8b0+149]
732f5e43: MSVCP90!std::basic_string<char,std::char_traits<char>,std::allocator<char> >::_Tidy [732f0000+5dfb+48]
732f5ec4: MSVCP90!std::basic_string<char,std::char_traits<char>,std::allocator<char> >::~basic_string<char,std::char_traits<char>,std::allocator<char> > [732f0000+5ebb+9]
005a1029: main() [00400000+1a0170+eb9]
751e36c5: MSVCR90!_set_flsgetvalue [751c0000+236b6+f]
751e38b3: MSVCR90!initptd [751c0000+23753+160]
752267ab: MSVCR90!realloc [751c0000+66415+396]
005bbf85: WinMain@16() [00400000+1bbf70+15]
007a3c0f: __tmainCRTStartup() [00400000+3a3acf+140]
779c9f45: ntdll!RtlInitializeExceptionChain [77990000+39f0f+36]

Static log:
StepMania v5.0 beta 3
Compiled 20140829 @ 11:19:38 Eastern Daylight Time (build 26)
Log starting 2014-08-30 16:48:21
Loading window: win32
Windows 6.1 (Win7) build 7601 [Service Pack 1]
Memory: 3966mb total, 4095mb swap (4095mb swap avail)
Video driver: NVIDIA GeForce 6150SE nForce 430 [NVIDIA]
              9.18.13.783, 1-31-2013 [pci\ven_10de&dev_03d0]
Drive: "Hitachi HDP725050GLA    GM4O" Driver: nvstor64 DMA: N/A
Drive: "ATAPI   DVD A  DH16AAL  LHD3" Driver: nvstor64 DMA: N/A
Sound device 0: Speakers (Realtek High Definiti, 6.1, MID 1, PID 100 
DirectSound Driver: Primary Sound Driver
DirectSound Driver: Speakers (Realtek High Definition Audio) {0.0.0.00000000}.{e695f95b-9a83-4802-b6b3-6096df3386fe}
DirectSound sample rates: 100..200000 (continuous)
Software mixing at 44100 hz
Sound driver: DirectSound-sw
Lights driver: SystemMessage
Lights driver: Export
Video renderers: 'opengl,d3d'
Mode: ICD 32 (888) 24 depth 64 accum 
Paletted textures disabled: GL_EXT_paletted_texture missing.
OGL Vendor: NVIDIA Corporation
OGL Renderer: GeForce 6150SE nForce 430/integrated/SSE2
OGL Version: 2.1.2
OGL Max texture size: 4096
OGL Texture units: 4
GLU Version: 1.2.2.0 Microsoft Corporation
OGL Extensions:
  GL_ARB: ES2_compatibility, color_buffer_float, compressed_texture_pixel_storage, conservative_depth, 
    copy_buffer, depth_clamp, depth_texture, draw_buffers, explicit_attrib_location, fragment_program, 
    fragment_program_shadow, fragment_shader, framebuffer_object, get_program_binary, half_float_pixel, 
    half_float_vertex, imaging, internalformat_query, map_buffer_alignment, map_buffer_range, multisample, 
    multitexture, occlusion_query, occlusion_query2, pixel_buffer_object, point_parameters, point_sprite, 
    provoking_vertex, robustness, sampler_objects, separate_shader_objects, shader_objects, shading_language_100, 
    shading_language_420pack, shading_language_include, shadow, sync, texture_border_clamp, texture_compression, 
    texture_cube_map, texture_env_add, texture_env_combine, texture_env_crossbar, texture_env_dot3, texture_float, 
    texture_mirrored_repeat, texture_non_power_of_two, texture_rectangle, texture_rg, texture_storage, 
    texture_swizzle, timer_query, transpose_matrix, vertex_array_bgra, vertex_array_object, vertex_buffer_object, 
    vertex_program, vertex_shader, window_pos
  GL_ATI: draw_buffers, texture_float, texture_mirror_once
  GL_EXT: Cg_shader, abgr, bgra, blend_color, blend_equation_separate, blend_func_separate, blend_minmax, 
    blend_subtract, compiled_vertex_array, depth_bounds_test, direct_state_access, draw_range_elements, fog_coord, 
    framebuffer_blit, framebuffer_multisample, framebuffer_object, gpu_program_parameters, import_sync_object, 
    multi_draw_arrays, packed_depth_stencil, packed_pixels, pixel_buffer_object, point_parameters, 
    provoking_vertex, rescale_normal, secondary_color, separate_shader_objects, separate_specular_color, 
    shadow_funcs, stencil_two_side, stencil_wrap, texture3D, texture_compression_dxt1, texture_compression_s3tc, 
    texture_cube_map, texture_edge_clamp, texture_env_add, texture_env_combine, texture_env_dot3, 
    texture_filter_anisotropic, texture_format_BGRA8888, texture_lod, texture_lod_bias, texture_mirror_clamp, 
    texture_object, texture_sRGB, texture_sRGB_decode, texture_storage, texture_swizzle, timer_query, 
    vertex_array, vertex_array_bgra
  GL_IBM: rasterpos_clip, texture_mirrored_repeat
  GL_KTX_buffer_region
  GL_NVX_conditional_render
  GL_NV: ES1_1_compatibility, alpha_test, blend_minmax, blend_square, complex_primitives, copy_depth_to_color, 
    depth_clamp, fbo_color_attachments, fence, float_buffer, fog_distance, fragdepth, fragment_program, 
    fragment_program2, fragment_program_option, framebuffer_multisample_coverage, half_float, light_max_exponent, 
    multisample_filter_hint, occlusion_query, packed_depth_stencil, pixel_data_range, point_sprite, 
    primitive_restart, register_combiners, register_combiners2, texgen_reflection, texture_barrier, 
    texture_compression_vtc, texture_env_combine4, texture_expand_normal, texture_lod_clamp, texture_rectangle, 
    texture_shader, texture_shader2, texture_shader3, vertex_array_range, vertex_array_range2, vertex_program, 
    vertex_program1_1, vertex_program2, vertex_program2_option, vertex_program3
  GL_OES: compressed_paletted_texture, depth24, depth32, depth_texture, element_index_uint, fbo_render_mipmap, 
    get_program_binary, mapbuffer, packed_depth_stencil, point_size_array, point_sprite, read_format, rgb8_rgba8, 
    standard_derivatives, texture_3D, texture_float, texture_float_linear, texture_half_float, 
    texture_half_float_linear, texture_npot, vertex_array_object, vertex_half_float
  GL_S3_s3tc
  GL_SGIS: generate_mipmap, texture_lod
  GL_SGIX: depth_texture, shadow
  GL_SUN_slice_accum
  GL_WIN_swap_hint
  WGL_EXT_swap_control
OpenGL Windowed 1601x885 32 color 32 texture 60Hz NoVsync SmoothLines
DInput: Enumerating device - Type: 0x00000413 Instance Name: "Keyboard" Product Name: "Keyboard"
DInput: Enumerating device - Type: 0x00010114 Instance Name: "2 axis 10 button joystick" Product Name: "2 axis 10 button joystick"
DInput: Enumerating device - Type: 0x00000112 Instance Name: "Mouse" Product Name: "Mouse"
Found 3 DirectInput devices:
   0: 'Keyboard' axes: 0, hats: 0, buttons: 256 (buffered)
   1: '2 axis 10 button joystick' axes: 2, hats: 0, buttons: 10 (buffered)
   2: 'Mouse' axes: 3, hats: 0, buttons: 3 (buffered)
Attempting to connect to: www.stepmaniaonline.net, Port: 8765
Beginning to connect
Calling EzSockets:connect()
Back from ezsockets...
Server Version: 128 StepmaniaOnline.net
WARNING: No options in row "list,Steps" were selected, and no fallback row found; selected entry 0
WARNING: No options in row "list,Steps" were selected, and no fallback row found; selected entry 0
WARNING: No options in row "list,Steps" were selected, and no fallback row found; selected entry 0
WARNING: No options in row "list,Steps" were selected, and no fallback row found; selected entry 0
Mixing underruns: 1
Players joined: P1
Lost focus to: StepMania-SSE2.exe
Top Screen: ScreenNetSelectMusic
Language: en
Current renderer: OpenGL
Theme: default

Partial log:
01:49.623: 50 FPS, 50 av FPS, 5043 VPF, OpenGL
01:50.638: 50 FPS, 50 av FPS, 5078 VPF, OpenGL
01:51.462: RageSound: Load "/Songs/DDR AC 2ndMix Club 2 Japan/been so long/been so long.mp3" (precache: 0)
01:51.462: Starting thread: Streaming sound buffering
01:51.463: Found '/Songs/DDR AC 2ndMix Club 2 Japan/been so long/been so long.sm'
01:51.496: Sound "/Songs/DDR AC 2ndMix Club 2 Japan/been so long/been so long.mp3" has a start time 0.032000 seconds in the past
01:51.509: Approximate sound time: driver frame 4902189, m_pImpl->m_Queue frame 0..512 (dist 3795), closest position is 0
01:51.655: 50 FPS, 50 av FPS, 5141 VPF, OpenGL
01:52.672: 50 FPS, 50 av FPS, 5266 VPF, OpenGL
01:53.691: 50 FPS, 50 av FPS, 5260 VPF, OpenGL

-- End of report

Edit: Interesting... It seems to be working now... I reset the keys. It auto set them to slot 2. I deleted/moved to slot 1 and it worked fine.

Edit: I will try to test/debug this later on after I am done playing on pad.

Edit: I tried to reproduce it again with no luck... Maybe just a random glitch with input...

**Comment by concubidated** [comment] 2017-03-06 17:46
Since @SpoOkyMagician was unable to reproduce and no one else has reported this. Closing.

**Closed by concubidated** 2017-03-06 17:46 UTC
Labels: smo
