### ISSUE TITLE
[5.1] Profiles note speeds not saving

### ISSUE THREAD

**Issue by MicroTransactionsMatterToo** [stepmania/stepmania#1292] opened 2016-09-18 08:48 UTC
I usually play on a 4 Xmod modifier, however, the new default is 2.5 Mmod. Normally, I can change it, and once I finish at least one stepfile, the change will carry over. Now, this change does not persist.

**Comment by kyzentun** [comment] 2016-09-18 13:41
Are you actually using a profile?
Are you using a theme that was updated to work with the latest 5.1?

**Comment by MicroTransactionsMatterToo** [comment] 2016-09-18 15:12
Yes, the theme is the default one, and I've checked that my profile is set.

**Comment by kyzentun** [comment] 2016-09-18 15:52
If you create Save/LocalProfiles/00000000/notefield_prefs.lua and put
```return { speed_mod= 4, speed_type= "multiple"}``` in it, does it get loaded?

Did you modify the default theme with something that changes the LoadProfileCustom or SaveProfileCustom lua functions?

**Comment by MicroTransactionsMatterToo** [comment] 2016-09-18 21:20
No, it does not load correctly. I have checked, (I am using the factory default theme, with no modifications made outside of the ingame settings), and the SaveProfileCustom and LoadProfileCustom functions are not anywhere in the themes scripts.

**Comment by kyzentun** [comment] 2016-09-18 22:52
Replace ```Themes/_fallback/Scripts/02 lua_config_system.lua``` with [this version](http://kyzentun.tejat.net/random_junk/02%20lua_config_system.lua), which has debugging messages that should show up when a profile is loaded or saved.

**Comment by MicroTransactionsMatterToo** [comment] 2016-09-19 07:22
The script doesn't seem to have had an effect, however in `Themes/_fallback/Scripts/03\ notefield_prefs.lua` I found this

```lua
local notefield_default_prefs= {
	speed_mod= 250,
	speed_type= "maximum",
	hidden= false,
	hidden_offset= 120,
	sudden= false,
	sudden_offset= 190,
	fade_dist= 40,
	glow_during_fade= true,
	fov= 45,
	reverse= 1,
	rotation_x= 0,
	rotation_y= 0,
	rotation_z= 0,
	vanish_x= 0,
	vanish_y= 0,
	yoffset= 130,
	zoom= 1,
	zoom_x= 1,
	zoom_y= 1,
	zoom_z= 1,
	-- migrated_from_newfield_name is temporary, remove it in 5.1.-4. -Kyz
	migrated_from_newfield_name= false,
}
```

This may be unrelated, but thought it may help

**Comment by MicroTransactionsMatterToo** [comment] 2016-09-19 07:24
Note, after changing the above to

```lua
local notefield_default_prefs= {
    speed_mod= 4,
    speed_type= "multiple",
    hidden= false,
    hidden_offset= 120,
    sudden= false,
    sudden_offset= 190,
    fade_dist= 40,
    glow_during_fade= true,
    fov= 45,
    reverse= 1,
    rotation_x= 0,
    rotation_y= 0,
    rotation_z= 0,
    vanish_x= 0,
    vanish_y= 0,
    yoffset= 130,
    zoom= 1,
    zoom_x= 1,
    zoom_y= 1,
    zoom_z= 1,
    -- migrated_from_newfield_name is temporary, remove it in 5.1.-4. -Kyz
    migrated_from_newfield_name= false,
}
```

It appears to have changed the default, giving me a temporary workaround

**Comment by kyzentun** [comment] 2016-09-19 14:23
Find ```Themes/_fallback/Scripts/01 profile_load_save.lua``` and change these two functions:
```
function LoadProfileCustom(profile, dir, pn)
	SCREENMAN:SystemMessage("LoadProfileCustom for " .. profile:GetDisplayName() .. ", " .. tostring(pn) .. ", " .. #profile_load_callbacks .. " callbacks.")
	for i, callback in ipairs(profile_load_callbacks) do
		callback(profile, dir, pn)
	end
end
function SaveProfileCustom(profile, dir, pn)
	SCREENMAN:SystemMessage("SaveProfileCustom for " .. profile:GetDisplayName() .. ", " .. tostring(pn) .. ", " .. #profile_save_callbacks .. " callbacks.")
	for i, callback in ipairs(profile_save_callbacks) do
		callback(profile, dir, pn)
	end
end
```

That should add some messages at the top of the screen to show that they're being called when loading and saving profiles.

If no messages show up, then the functions aren't being called.  Some other script in the theme you're using is redefining them, which needs to be dug out and updated properly.

**Comment by kyzentun** [comment] 2016-09-23 22:34
Closing because the user left without providing a way to reproduce the problem.

**Closed by kyzentun** 2016-09-23 22:34 UTC

**Comment by kyzentun** [comment] 2016-10-18 13:39
This commit is relevant to lua config not saving: https://github.com/stepmania/stepmania/commit/a4ae79f8e69fa3cfee09eb69077b0054e5aa7011

Prior to this, config data for a profile on a USB drive would not load correctly.
